---
title: "Sergey Samsonau"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    keep_md: true

---

I do and teach Physics and Data Science. 

## Recent papers

*  E. Mohlhenrich, S.V. Samsonau, R.P. Spencer, “Integrating Science Through Authentic Research in Secondary Schools”, IEEE Integrated STEM Education Conference, March 2018

* Thyroid Hormone Status in Stroke and Transient Ischemic Attack Patients.
    + Halinouskaya, N. V.; Samsonau, S. V.; Usava, N. N.; Smychek, V. B. Neurologijos Seminarai; 2015, Vol. 19 Issue 3, p207
    + [paper](http://connection.ebscohost.com/c/articles/110196910/thyroid-hormone-status-stroke-transient-ischemic-attack-patients), [code](supplementary_information.pdf)
    
## R projects {.tabset}
    
### By me

Some shiny apps created for experimental physics lab

  * [Spectroscopy](https://github.com/ssamsonau/Spectroscopy)
  * [Sample stage control](https://github.com/ssamsonau/SampleStage)
  * [Solar cell testing](https://github.com/ssamsonau/solar_cell_testing)

### By students (high school) under my mentorship

Projects done by students (high school) under my mentorship

* Renewable Energy exploration. Big Data Challenge.
    + [shiny app](https://www.google.com/url?q=https%3A%2F%2Fgk-233.shinyapps.io%2FBigData_PRISMS%2F&sa=D&sntz=1&usg=AFQjCNEAbs3g1Mc6kaYlabY9_ByPYmjl2g)

* Automating Reconstruction of Focused Ion Beam Current Density Distribution
    + poster presented at FIBSEM meeting on March, 2017 (X. Li, S. Samsonau, E. Chang, V. Ray)
    + [see poster](http://www.fibsem.net/web_documents/2017Presentations/P08-Ray-PBS-poster.pdf)
    + [interactive application](https://cloud.ket-labs.com/shiny/FIB/)
    + code - work in progress, please ask

* Correlation between emotional factors and the stock market
    + [report](https://github.com/prismsus/HighFrequency/blob/master/Final_Presentation.Rmd)
    + [poster](https://github.com/prismsus/HighFrequency/blob/master/poster/Final_poster.pdf)
    + [code](https://github.com/prismsus/HighFrequency)
    
* Detecting fraud in election by statistical method
    + [report](https://github.com/prismsus/election/blob/master/presentation.md)
    + [code](https://github.com/prismsus/election)

## Data Science class {.tabset}

Data Science class I developed and teach

### Data Science I

Data Science I course is designed to teach students analyze data using R language, as well as how to present results of analysis. Data in the modern world are coming from different sources and in different formats. Data can be obtained from sensors, collected via a survey, stored in a database, or wait to be downloaded from Internet. Often such data will have a “messy” structure, there will be missing values, etc. Students will learn how to access data from various sources, reshape, organize and clean it. Basic statistical information and plots will be employed to make an initial exploratory analysis. We shall cover techniques for creation of highly customized professionally looking plots. Students will learn to create interactive plots and interactive web applications (using R Shiny), to present data visually to a wide auditory. Linear model will be used to perform a basic modeling. This class involves a lot of coding and practical exercises in R.    
_Textbook_: R for Data Science: Import, Tidy, Transform, Visualize, and Model Data (Authors: Hadley Wickham, Garrett Grolemund)

### Data Science II 
covers selected topics of machine learning. When data is cleaned and understood (covered in Data Science I) it is possible to create a “prediction” model: calculate a projected salary, classify emails to spam or ham, find “clusters” of friends on Facebook, detect a fraud transaction on a credit card, etc.Students will obtain skills in doing regression, classification, clustering and anomaly detection. The following algorithms will be covered: k-nearest neighborhoods, linear model, logistic regression, LDA, QDA, polynomial regression, splines, GAMs, tree-based methods, SVM. The coverage will include resampling methods, regularization, principal components, text mining.    
_Textbook_: An Introduction to Statistical Learning with Applications in R (Authors: James, G., Witten, D., Hastie, T., Tibshirani, R). 


## Training Program for PhDs
I developed and taught (in January and June of 2016) a 35-hours (5 days) “Essentials of Data Science” training program for PhD-students and Postdocs (twice at Columbia University). More details can be found here [Ket Labs](http://www.ket-labs.com/)   
    
* Some of projects created by participants of this training
    + [ket-labs.com/examples/](http://www.ket-labs.com/examples/)
    
* A collaborative project
    + [Predictive Wavelength Switching](https://github.com/Zahra-Bakhtiari/Predictive-Wavelength-Switching/blob/master/Main-Algorithm.md)
    


## Older code/projects

__Kaggle Machine learning competitions (2014, Aug - 2015, March)__

* Plankton classification (NDSB) 
    + [code on GitHub](https://github.com/ssamsonau/NDSB) (extraction of features from images, use of random forest for prediction)

* Click-Through Rate Prediction for adds 
    + [code on GitHub](https://github.com/ssamsonau/ClickThrough/tree/h2o)
(features subsetting, Deep learning (from h2o package)) 
    + [code on GitHub](https://github.com/ssamsonau/ClickThrough/tree/caret) (features subsetting, Neural Network (caret package)) 

* American Epilepsy Society Seizure Prediction Challenge 
    + [code on GitHub](https://github.com/ssamsonau/K_Epil) (SVM, FFT)

* Identifying Higgs boson in ATLAS data 
    + [code on GitHub](https://github.com/ssamsonau/K_Higgs) (Neural Network, work with features, learning curves)
    
## Links

+  [LinkedIn](http://linkedin.com/in/ssamsonau)
+  [GitHub](https://github.com/ssamsonau)
+  [Ket Labs](http://www.ket-labs.com/)  
