---
title: "Teaching"
date: 2018-04-22
---

## Physics

* Algebra-based Physics (college and high school)
* Calculus-based Physics (college and high school)
* Quantum Mechanics (high school)
* I did setup and now supervise a nanotechnology research laboratory at a high school
* A course of labs designed to develop student's research skill was developed and will be described soon 
* A course of labs combining numerical simulations with experiments which I developed will be soon availabe on arxiv.org

## Data Science

* Data Science class I did introduce and teach at a high school
* I did organize and now supervise Data Science research laboratory at a high school

### Data Science I

Data Science I course is designed to teach students analyze data using R language, as well as how to present results of analysis. Data in the modern world are coming from different sources and in different formats. Data can be obtained from sensors, collected via a survey, stored in a database, or wait to be downloaded from Internet. Often such data will have a "messy" structure, there will be missing values, etc. Students will learn how to access data from various sources, reshape, organize and clean it. Basic statistical information and plots will be employed to make an initial exploratory analysis. We shall cover techniques for creation of highly customized professionally looking plots. Students will learn to create interactive plots and interactive web applications (using R Shiny), to present data visually to a wide auditory. Linear model will be used to perform a basic modeling. This class involves a lot of coding and practical exercises in R.    
_Textbook_: R for Data Science: Import, Tidy, Transform, Visualize, and Model Data (Authors: Hadley Wickham, Garrett Grolemund)

### Data Science II 
covers selected topics of machine learning. When data is cleaned and understood (covered in Data Science I) it is possible to create a "prediction" model: calculate a projected salary, classify emails to spam or ham, find "clusters" of friends on Facebook, detect a fraud transaction on a credit card, etc. Students will obtain skills in doing regression, classification, clustering and anomaly detection. The following algorithms will be covered: k-nearest neighborhoods, linear model, logistic regression, LDA, QDA, polynomial regression, splines, GAMs, tree-based methods, SVM. The coverage will include resampling methods, regularization, principal components, text mining.    
_Textbook_: An Introduction to Statistical Learning with Applications in R (Authors: James, G., Witten, D., Hastie, T., Tibshirani, R). 

### EDS training program 

I (with two colleagues) developed and taught (in January and June of 2016) a 35-hours (5 days) "Essentials of Data Science" training program for PhD-students and Postdocs (twice at Columbia University). More details can be found here [Ket Labs](http://www.ket-labs.com/)   

